### ISSUE TITLE
Install Issue with pytorch1.5.0

### ISSUE THREAD

**Issue by layumi** [erikwijmans/Pointnet2_PyTorch#105]
Hi, thanks a lot for the great code. 

I meet one install question with pytorch 1.5.0, cuda 10.1  after running `pip install -r requirements.txt` as follows:

```
  building 'pointnet2_ops._ext' extension
  Emitting ninja build file /tmp/pip-req-build-lbep38x1/build/temp.linux-x86_64-3.6/build.ninja...
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-lbep38x1/setup.py", line 37, in <module>
      include_package_data=True,
    File "/home/zzd/anaconda3/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/home/zzd/anaconda3/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/zzd/anaconda3/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/zzd/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/zzd/anaconda3/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/home/zzd/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/zzd/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/zzd/anaconda3/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/zzd/anaconda3/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/zzd/anaconda3/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/zzd/anaconda3/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 78, in run
      _build_ext.run(self)
    File "/home/zzd/anaconda3/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
      _build_ext.build_ext.run(self)
    File "/home/zzd/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/home/zzd/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 580, in build_extensions
      build_ext.build_extensions(self)
    File "/home/zzd/anaconda3/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 194, in build_extensions
      self.build_extension(ext)
    File "/home/zzd/anaconda3/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 199, in build_extension
      _build_ext.build_extension(self, ext)
    File "/home/zzd/anaconda3/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
      depends=ext.depends)
    File "/home/zzd/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 423, in unix_wrap_ninja_compile
      with_cuda=with_cuda)
    File "/home/zzd/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1132, in _write_ninja_file_and_compile_objects
      with_cuda=with_cuda)
    File "/home/zzd/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1560, in _write_ninja_file
      assert len(sources) > 0
  AssertionError
  ----------------------------------------
  ERROR: Failed building wheel for pointnet2-ops
  Running setup.py clean for pointnet2-ops
```

**Comment by layumi** [comment]
Solve it via degrade pytorch to `1.4.0`
