### ISSUE TITLE
Error using Hydra

### ISSUE THREAD

**Issue by pvnieo** [erikwijmans/Pointnet2_PyTorch#113]
Hi,

Thank you for the amazing implementation.

I'm using pointNet2 as a feature extractor in a separate project, and I got inspired by your implementation using Hydra, and how it made the implementation clear and readable, and I want to use it in my project.
However, I got an error and I want to know if you got the same error, and how to avoid it. The error is:
```
File "/home/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/training_io.py", line 353, in dump_checkpoint
    raise ValueError(
ValueError: ('The acceptable hparams type is dict or argparse.Namespace,', ' not DictConfig')
Exception ignored in: <function tqdm.__del__ at 0x7f1f9e379a60>
```
Thank you in advance.

**Comment by erikwijmans** [comment]
https://github.com/erikwijmans/Pointnet2_PyTorch/blob/f71dc83fbca9dd55201e3489a3bcc92d3bdf908c/pointnet2/train.py#L13-L31

**Comment by pvnieo** [comment]
Thank you for your response. Actually, I used this and I still got the error.
Maybe I'm using a different version from you.

**Comment by kaixin-bai** [comment]
same problem for me.
`98 | fc_lyaer.4              | Conv1d           | 1 K   
Epoch 1: 100%|█████████████| 983/983 [02:38<00:00,  6.19it/s, loss=0.554, train_acc=0.765, v_num=3, val_acc=0.81, val_loss=0.654]
Epoch 00000: val_acc reached 0.80962 (best 0.80962), saving model to sem-ssg/epoch=0-val_loss=0.65-val_acc=0.810.ckpt as top 2   
[2020-06-10 13:21:11,283][lightning][INFO] - 
Epoch 00000: val_acc reached 0.80962 (best 0.80962), saving model to sem-ssg/epoch=0-val_loss=0.65-val_acc=0.810.ckpt as top 2
/home/kb/.local/lib/python3.6/site-packages/torch/optim/lr_scheduler.py:200: UserWarning: Please also save or load the state of the optimzer when saving or loading the scheduler.
  warnings.warn(SAVE_STATE_WARNING, UserWarning)
Traceback (most recent call last):
  File "pointnet2/train.py", line 61, in <module>
    main()
  File "/home/kb/.local/lib/python3.6/site-packages/hydra/main.py", line 24, in decorated_main
    strict=strict,
  File "/home/kb/.local/lib/python3.6/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
    overrides=args.overrides,
  File "/home/kb/.local/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 86, in run
    job_subdir_key=None,
  File "/home/kb/.local/lib/python3.6/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "pointnet2/train.py", line 57, in main
    trainer.fit(model)
  File "/home/kb/.local/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 853, in fit
    self.dp_train(model)
  File "/home/kb/.local/lib/python3.6/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 578, in dp_train
    self.run_pretrain_routine(model)
  File "/home/kb/.local/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 1015, in run_pretrain_routine
    self.train()
  File "/home/kb/.local/lib/python3.6/site-packages/pytorch_lightning/trainer/training_loop.py", line 347, in train
    self.run_training_epoch()
  File "/home/kb/.local/lib/python3.6/site-packages/pytorch_lightning/trainer/training_loop.py", line 452, in run_training_epoch
    self.call_checkpoint_callback()
  File "/home/kb/.local/lib/python3.6/site-packages/pytorch_lightning/trainer/training_loop.py", line 790, in call_checkpoint_callback
    self.checkpoint_callback.on_validation_end(self, self.get_model())
  File "/home/kb/.local/lib/python3.6/site-packages/pytorch_lightning/utilities/distributed.py", line 10, in wrapped_fn
    return fn(*args, **kwargs)
  File "/home/kb/.local/lib/python3.6/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 241, in on_validation_end
    self._do_check_save(filepath, current, epoch)
  File "/home/kb/.local/lib/python3.6/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 275, in _do_check_save
    self._save_model(filepath)
  File "/home/kb/.local/lib/python3.6/site-packages/pytorch_lightning/callbacks/model_checkpoint.py", line 142, in _save_model
    self.save_function(filepath)
  File "/home/kb/.local/lib/python3.6/site-packages/pytorch_lightning/trainer/training_io.py", line 260, in save_checkpoint
    checkpoint = self.dump_checkpoint()
  File "/home/kb/.local/lib/python3.6/site-packages/pytorch_lightning/trainer/training_io.py", line 355, in dump_checkpoint
    f' not {checkpoint["hparams_type"]}'
ValueError: ('The acceptable hparams type is dict or argparse.Namespace,', ' not DictConfig')
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/kb/.local/lib/python3.6/site-packages/tqdm/std.py", line 1086, in __del__
  File "/home/kb/.local/lib/python3.6/site-packages/tqdm/std.py", line 1293, in close
  File "/home/kb/.local/lib/python3.6/site-packages/tqdm/std.py", line 1471, in display
  File "/home/kb/.local/lib/python3.6/site-packages/tqdm/std.py", line 1089, in __repr__
  File "/home/kb/.local/lib/python3.6/site-packages/tqdm/std.py", line 1433, in format_dict
TypeError: 'NoneType' object is not iterable`
