### ISSUE TITLE
pytorch_lightning.utilities.debugging.MisconfigurationException

### ISSUE THREAD

**Issue by oh-y** [erikwijmans/Pointnet2_PyTorch#120]
- Hi, I encountered the problem with pytorch_lightning.  Can anyone help?  Thanks!
```
Traceback (most recent call last):
  File "/datah/pc/Pointnet2_PyTorch/pointnet2/train.py", line 61, in <module>
    main()
  File "/datah/soft/anaconda3/envs/env2/lib/python3.6/site-packages/hydra/main.py", line 24, in decorated_main
    strict=strict,
  File "/datah/soft/anaconda3/envs/env2/lib/python3.6/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
    overrides=args.overrides,
  File "/datah/soft/anaconda3/envs/env2/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 86, in run
    job_subdir_key=None,
  File "/datah/soft/anaconda3/envs/env2/lib/python3.6/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "/datah/pc/Pointnet2_PyTorch/pointnet2/train.py", line 54, in main
    distributed_backend=cfg.distrib_backend,
  File "/datah/soft/anaconda3/envs/env2/lib/python3.6/site-packages/pytorch_lightning/trainer/trainer.py", line 366, in __init__
    self.data_parallel_device_ids = parse_gpu_ids(self.gpus)
  File "/datah/soft/anaconda3/envs/env2/lib/python3.6/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 622, in parse_gpu_ids
    gpus = sanitize_gpu_ids(gpus)
  File "/datah/soft/anaconda3/envs/env2/lib/python3.6/site-packages/pytorch_lightning/trainer/distrib_parts.py", line 592, in sanitize_gpu_ids
    raise MisconfigurationException(message)
pytorch_lightning.utilities.debugging.MisconfigurationException: 
            You requested GPUs: [0]
            But your machine only has: []
```

- my environment packages
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
absl-py                   0.9.0                     <pip>
blessings                 1.7                       <pip>
ca-certificates           2020.1.1                      0    defaults
cachetools                4.1.0                     <pip>
certifi                   2020.4.5.1               py36_0    defaults
chardet                   3.0.4                     <pip>
future                    0.18.2                    <pip>
google-auth               1.14.3                    <pip>
google-auth-oauthlib      0.4.1                     <pip>
gpustat                   0.6.0                     <pip>
grpcio                    1.28.1                    <pip>
h5py                      2.10.0                    <pip>
hydra-core                0.11.3                    <pip>
idna                      2.9                       <pip>
importlib-metadata        1.6.0                     <pip>
ld_impl_linux-64          2.33.1               h53a641e_7    defaults
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.3                  he6710b0_1    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
lmdb                      0.98                      <pip>
Markdown                  3.2.2                     <pip>
msgpack                   1.0.0                     <pip>
msgpack-numpy             0.4.5                     <pip>
ncurses                   6.2                  he6710b0_1    defaults
numpy                     1.18.4                    <pip>
nvidia-ml-py3             7.352.0                   <pip>
oauthlib                  3.1.0                     <pip>
omegaconf                 1.4.1                     <pip>
openssl                   1.1.1g               h7b6447c_0    defaults
Pillow                    7.1.2                     <pip>
pip                       20.0.2                   py36_3    defaults
pointnet2-ops             3.0.0                     <pip>
protobuf                  3.11.3                    <pip>
psutil                    5.7.0                     <pip>
pyasn1                    0.4.8                     <pip>
pyasn1-modules            0.2.8                     <pip>
python                    3.6.10               h7579374_2    defaults
pytorch-lightning         0.7.1                     <pip>
readline                  8.0                  h7b6447c_0    defaults
requests                  2.23.0                    <pip>
requests-oauthlib         1.3.0                     <pip>
rsa                       4.0                       <pip>
setuptools                46.2.0                   py36_0    defaults
six                       1.14.0                    <pip>
sqlite                    3.31.1               h62c20be_1    defaults
tensorboard               2.2.1                     <pip>
tensorboard-plugin-wit    1.6.0.post3               <pip>
tk                        8.6.8                hbc83047_0    defaults
torch                     1.5.0                     <pip>
torchvision               0.6.0                     <pip>
tqdm                      4.46.0                    <pip>
urllib3                   1.25.9                    <pip>
Werkzeug                  1.0.1                     <pip>
wheel                     0.34.2                   py36_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
zipp                      3.1.0                     <pip>
zlib                      1.2.11               h7b6447c_3    defaults
```

**Comment by erikwijmans** [comment]
```
pytorch_lightning.utilities.debugging.MisconfigurationException: 
            You requested GPUs: [0]
            But your machine only has: []
```

Sounds like you are trying to run this on a machine without a GPU?  The custom ops for PointNet++ are only implemented for the GPU, so this repo does not support CPU-only.

**Comment by oh-y** [comment]
I checked this. It's a machine with 4 GPUs but cannot display.  I don't know and will keep looking for the reasons.  Thanks!
![image](https://user-images.githubusercontent.com/27051975/86549814-3b953580-bf73-11ea-9b5e-8dc918438daf.png)
