### ISSUE TITLE
how to test？

### ISSUE THREAD

**Issue by AndrewJSong** [erikwijmans/Pointnet2_PyTorch#126]
I had trained this network，but I don not konw how to test it,can you provide the mothod.THANK YOU

**Comment by pengPeterpeng** [comment]
hi, I think the data Loader file uses the test dataset as the validation dataset. If you want to test the network, I think you can edit the "tests/conftest.py"

**Comment by albertotono** [comment]
@AndrewJSong did you succedded in this? When I am trying to run the train I got this 
```

  File "pointnet2/train.py", line 31, in main
    model = hydra.utils.instantiate(cfg.task_model, hydra_params_to_dotdict(cfg))
  File "/home/alberto/anaconda3/envs/pointnet++/lib/python3.8/site-packages/hydra/utils.py", line 70, in call
    raise HydraException(f"Error calling '{cls}' : {e}") from e
hydra.errors.HydraException: Error calling 'pointnet2.models.PointNet2SemSegSSG' : __init__() got an unexpected keyword argument 'name'

```

**Comment by Rishab9991** [comment]
@AndrewJSong I tried running the conftest.py file but getting the following error

**Traceback (most recent call last):
  File "conftest.py", line 16, in <module>
    @pytest.helpers.register
AttributeError: module 'pytest' has no attribute 'helpers'**

Were you able to resolve this error?
