### ISSUE TITLE
How to run "pip install pointnet2_ops_lib/." under the version of PyTorch 1.7.0?

### ISSUE THREAD

**Issue by HeBangYan** [erikwijmans/Pointnet2_PyTorch#155]
I am using ubuntu18.04 python 3.7 pytorch 1.7.0. cuda 10.2.

When I use this command, these errors will be reported:
> Processing ./pointnet2_ops_lib
Building wheels for collected packages: pointnet2
  Building wheel for pointnet2 (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/bangyanhe/anaconda3/envs/pt_1.7/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-7i722xyk/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-7i722xyk/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-kjqo6fm0
       cwd: /tmp/pip-req-build-7i722xyk/
  Complete output (50 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'pointnet2._ext' extension
  Emitting ninja build file /tmp/pip-req-build-7i722xyk/build/temp.linux-x86_64-3.7/build.ninja...
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-7i722xyk/setup.py", line 32, in <module>
      'build_ext': BuildExtension
    File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
      _build_ext.run(self)
    File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 653, in build_extensions
      build_ext.build_extensions(self)
    File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
      _build_ext.build_extension(self, ext)
    File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
      depends=ext.depends)
    File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 482, in unix_wrap_ninja_compile
      with_cuda=with_cuda)
    File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1230, in _write_ninja_file_and_compile_objects
      with_cuda=with_cuda)
    File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1697, in _write_ninja_file
      assert len(sources) > 0
  AssertionError

>  ERROR: Failed building wheel for pointnet2
  Running setup.py clean for pointnet2
Failed to build pointnet2
Installing collected packages: pointnet2
    Running setup.py install for pointnet2 ... error
    ERROR: Command errored out with exit status 1:
     command: /home/bangyanhe/anaconda3/envs/pt_1.7/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-7i722xyk/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-7i722xyk/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-x12unf7s/install-record.txt --single-version-externally-managed --compile --install-headers /home/bangyanhe/anaconda3/envs/pt_1.7/include/python3.7m/pointnet2
         cwd: /tmp/pip-req-build-7i722xyk/
    Complete output (52 lines):
    running install
    running build
    running build_ext
    building 'pointnet2._ext' extension
    Emitting ninja build file /tmp/pip-req-build-7i722xyk/build/temp.linux-x86_64-3.7/build.ninja...
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-7i722xyk/setup.py", line 32, in <module>
        'build_ext': BuildExtension
      File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 653, in build_extensions
        build_ext.build_extensions(self)
      File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
        depends=ext.depends)
      File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 482, in unix_wrap_ninja_compile
        with_cuda=with_cuda)
      File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1230, in _write_ninja_file_and_compile_objects
        with_cuda=with_cuda)
      File "/home/bangyanhe/anaconda3/envs/pt_1.7/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1697, in _write_ninja_file
        assert len(sources) > 0
    AssertionError

> ERROR: Command errored out with exit status 1: /home/bangyanhe/anaconda3/envs/pt_1.7/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-7i722xyk/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-7i722xyk/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-x12unf7s/install-record.txt --single-version-externally-managed --compile --install-headers /home/bangyanhe/anaconda3/envs/pt_1.7/include/python3.7m/pointnet2 Check the logs for full command output.

**Comment by HeBangYan** [comment]
The problem has been solved.
I refer to [Quan-dao's answer](https://github.com/sshaoshuai/Pointnet2.PyTorch/issues/26). Also update `ninja to version 1.7.2 and GCC /g++ to version 5.5.0.`
