### ISSUE TITLE
No module named 'pointnet2'

### ISSUE THREAD

**Issue by rabbiahassan** [erikwijmans/Pointnet2_PyTorch#156]
Hello !
I executed the pip install -r requirements.txt and it doesn't produce any error.But when I tried to start training it produces the follwoing error.
2_PyTorch-master/pointnet2$ python3.6 train.py task=cls
[2021-09-21 01:43:05,716][hydra.utils][ERROR] - Error instantiating pointnet2.models.PointNet2ClassificationSSG : No module named 'pointnet2'
Traceback (most recent call last):
  File "train.py", line 55, in <module>
    main()
  File "/home/seecs/.local/lib/python3.6/site-packages/hydra/main.py", line 24, in decorated_main
    strict=strict,
  File "/home/seecs/.local/lib/python3.6/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
    overrides=args.overrides,
  File "/home/seecs/.local/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 86, in run
    job_subdir_key=None,
  File "/home/seecs/.local/lib/python3.6/site-packages/hydra/plugins/common/utils.py", line 109, in run_job
    ret.return_value = task_function(task_cfg)
  File "train.py", line 31, in main
    model = hydra.utils.instantiate(cfg.task_model, hydra_params_to_dotdict(cfg))
  File "/home/seecs/.local/lib/python3.6/site-packages/hydra/utils.py", line 60, in instantiate
    raise e
  File "/home/seecs/.local/lib/python3.6/site-packages/hydra/utils.py", line 49, in instantiate
    clazz = get_class(config["class"])
  File "/home/seecs/.local/lib/python3.6/site-packages/hydra/utils.py", line 21, in get_class
    mod = import_module(module_path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pointnet2'
Can you please guide?
Thanks for your time.

**Comment by gamzekiprit** [comment]
Hey, i also faced the same problem. Did you solve it? Thanks!

**Comment by besim21** [comment]
Hello, I am facing the same issue. Were you able to solve it? if yes, I'd appreciate your help. Thanks

**Comment by JianrongYan** [comment]
No answers yet? I also met this issue.

**Comment by swaidan** [comment]
Hi,  you might have missed this step in the installation (check the first line of "Example training" in the README of the repo):
`pip install -e .`
I hope that solves the issue

**Comment by KhairilAriffinYahya** [comment]
So im running into same issue. Anyone found solution to this?

**Comment by JianrongYan** [comment]
> So im running into same issue. Anyone found solution to this?

i have solved this issue. The main reason is your setuptools version is too high, so you can lower your setuptools version by running "pip install setuptools==58.2.0".

**Comment by LiXiaoYao-0** [comment]
> 

can you tell me what version of cuda、pytorch and python you use? i have been having trouble installing it.

**Comment by LiXiaoYao-0** [comment]
> > So im running into same issue. Anyone found solution to this?
> 
> i have solved this issue. The main reason is your setuptools version is too high, so you can lower your setuptools version by running "pip install setuptools==58.2.0".

can you tell me what version of cuda、pytorch and python you use? i have been having trouble installing it.

**Comment by hyl510** [comment]
> > So im running into same issue. Anyone found solution to this?
> 
> i have solved this issue. The main reason is your setuptools version is too high, so you can lower your setuptools version by running "pip install setuptools==58.2.0".

I have lower the setuptools and it didn't work. Should reinstall all the packages?

**Comment by hyl510** [comment]
I got it! First install setuptools==58.2.0, and then run "python setup.py install". You can use command "python setup.py ----help-commands" to see all the available commands.

**Comment by airobot1024** [comment]
> > So im running into same issue. Anyone found solution to this?
> 
> i have solved this issue. The main reason is your setuptools version is too high, so you can lower your setuptools version by running "pip install setuptools==58.2.0".

pip install setuptools==58.2.0, it resolve my issues. Many thinks!
