### ISSUE TITLE
How to build with CUDA9.0 ?

### ISSUE THREAD

**Issue by guess-who-ami** [erikwijmans/Pointnet2_PyTorch#163]
copying pointnet2_ops/_ext-src/src/sampling_gpu.cu -> build/lib.linux-x86_64-3.6/pointnet2_ops/_ext-src/src
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/yuenlin/documents/PVN3D-master/Pointnet2_PyTorch-master/pointnet2_ops_lib/setup.py", line 38, in <module>
        include_package_data=True,
      File "/home/yuenlin/.venvs/pvn3dmaster/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/yuenlin/.venvs/pvn3dmaster/lib/python3.6/site-packages/setuptools/command/install.py", line 68, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/yuenlin/.venvs/pvn3dmaster/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/yuenlin/.venvs/pvn3dmaster/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/home/yuenlin/.venvs/pvn3dmaster/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 404, in build_extensions
        self._check_cuda_version()
      File "/home/yuenlin/.venvs/pvn3dmaster/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 781, in _check_cuda_version
        raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))

    RuntimeError:
    The detected CUDA version (9.0) mismatches the version that was used to compile
    PyTorch (10.2). Please make sure to use the same CUDA versions.

**i use pytotch 1.0.1 and CUDA9.0, but failed to building wheel for pointnet2-ops**

**Comment by gargsid** [comment]
> ```
> copying pointnet2_ops/_ext-src/src/sampling_gpu.cu -> build/lib.linux-x86_64-3.6/pointnet2_ops/_ext-src/src
> running build_ext
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/yuenlin/documents/PVN3D-master/Pointnet2_PyTorch-master/pointnet2_ops_lib/setup.py", line 38, in <module>
>     include_package_data=True,
>   File "/home/yuenlin/.venvs/pvn3dmaster/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
>     return distutils.core.setup(**attrs)
>   File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
>     dist.run_commands()
>   File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
>     self.run_command(cmd)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/home/yuenlin/.venvs/pvn3dmaster/lib/python3.6/site-packages/setuptools/command/install.py", line 68, in run
>     return orig.install.run(self)
>   File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
>     self.run_command('build')
>   File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
>     self.run_command(cmd_name)
>   File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/home/yuenlin/.venvs/pvn3dmaster/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 79, in run
>     _build_ext.run(self)
>   File "/home/yuenlin/.venvs/pvn3dmaster/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
>     _build_ext.build_ext.run(self)
>   File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
>     self.build_extensions()
>   File "/home/yuenlin/.venvs/pvn3dmaster/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 404, in build_extensions
>     self._check_cuda_version()
>   File "/home/yuenlin/.venvs/pvn3dmaster/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 781, in _check_cuda_version
>     raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
> 
> RuntimeError:
> The detected CUDA version (9.0) mismatches the version that was used to compile
> PyTorch (10.2). Please make sure to use the same CUDA versions.
> ```
> 
> **i use pytotch 1.0.1 and CUDA9.0, but failed to building wheel for pointnet2-ops**

Did you solve this? I am having the same problem.

**Comment by FUIGUIMURONG** [comment]
> ```
> copying pointnet2_ops/_ext-src/src/sampling_gpu.cu -> build/lib.linux-x86_64-3.6/pointnet2_ops/_ext-src/src
> running build_ext
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/home/yuenlin/documents/PVN3D-master/Pointnet2_PyTorch-master/pointnet2_ops_lib/setup.py", line 38, in <module>
>     include_package_data=True,
>   File "/home/yuenlin/.venvs/pvn3dmaster/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
>     return distutils.core.setup(**attrs)
>   File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
>     dist.run_commands()
>   File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
>     self.run_command(cmd)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/home/yuenlin/.venvs/pvn3dmaster/lib/python3.6/site-packages/setuptools/command/install.py", line 68, in run
>     return orig.install.run(self)
>   File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
>     self.run_command('build')
>   File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
>     self.run_command(cmd_name)
>   File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>     self.distribution.run_command(command)
>   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>     cmd_obj.run()
>   File "/home/yuenlin/.venvs/pvn3dmaster/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 79, in run
>     _build_ext.run(self)
>   File "/home/yuenlin/.venvs/pvn3dmaster/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
>     _build_ext.build_ext.run(self)
>   File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
>     self.build_extensions()
>   File "/home/yuenlin/.venvs/pvn3dmaster/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 404, in build_extensions
>     self._check_cuda_version()
>   File "/home/yuenlin/.venvs/pvn3dmaster/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 781, in _check_cuda_version
>     raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
> 
> RuntimeError:
> The detected CUDA version (9.0) mismatches the version that was used to compile
> PyTorch (10.2). Please make sure to use the same CUDA versions.
> ```
> 
> **i use pytotch 1.0.1 and CUDA9.0, but failed to building wheel for pointnet2-ops**

I want to ask do you solve this? I am having the same problem

**Comment by FUIGUIMURONG** [comment]
> > ```
> > copying pointnet2_ops/_ext-src/src/sampling_gpu.cu -> build/lib.linux-x86_64-3.6/pointnet2_ops/_ext-src/src
> > running build_ext
> > Traceback (most recent call last):
> >   File "<string>", line 1, in <module>
> >   File "/home/yuenlin/documents/PVN3D-master/Pointnet2_PyTorch-master/pointnet2_ops_lib/setup.py", line 38, in <module>
> >     include_package_data=True,
> >   File "/home/yuenlin/.venvs/pvn3dmaster/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
> >     return distutils.core.setup(**attrs)
> >   File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
> >     dist.run_commands()
> >   File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
> >     self.run_command(cmd)
> >   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
> >     cmd_obj.run()
> >   File "/home/yuenlin/.venvs/pvn3dmaster/lib/python3.6/site-packages/setuptools/command/install.py", line 68, in run
> >     return orig.install.run(self)
> >   File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
> >     self.run_command('build')
> >   File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
> >     self.distribution.run_command(command)
> >   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
> >     cmd_obj.run()
> >   File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
> >     self.run_command(cmd_name)
> >   File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
> >     self.distribution.run_command(command)
> >   File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
> >     cmd_obj.run()
> >   File "/home/yuenlin/.venvs/pvn3dmaster/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 79, in run
> >     _build_ext.run(self)
> >   File "/home/yuenlin/.venvs/pvn3dmaster/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
> >     _build_ext.build_ext.run(self)
> >   File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
> >     self.build_extensions()
> >   File "/home/yuenlin/.venvs/pvn3dmaster/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 404, in build_extensions
> >     self._check_cuda_version()
> >   File "/home/yuenlin/.venvs/pvn3dmaster/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 781, in _check_cuda_version
> >     raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
> > 
> > RuntimeError:
> > The detected CUDA version (9.0) mismatches the version that was used to compile
> > PyTorch (10.2). Please make sure to use the same CUDA versions.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **i use pytotch 1.0.1 and CUDA9.0, but failed to building wheel for pointnet2-ops**
> 
> Did you solve this? I am having the same problem.

hello, do you solve this, I am having the same problem

**Comment by jurastm** [comment]
same problem. has anyone solved?
