### ISSUE TITLE
ImportError：_pointnet2.so: undefined symbol: PyInt_FromLong

### ISSUE THREAD

**Issue by smmdream** [erikwijmans/Pointnet2_PyTorch#18]
hi erikwijmans:
environment of my computer is ubuntu16.04, cuda9.0 pytorch0.4.1 and gtx 1060
I just follow your steps:
1.mkdir build && cd build
2.cmake .. && make
and successful
But when I run the train_sem_seg.py , I got the error.
/usr/bin/python3.5 /home/mengzhen/PointNet/Pointnet2_PyTorch/pointnet2/train/train_sem_seg.py
Traceback (most recent call last):
  File "/home/mengzhen/PointNet/Pointnet2_PyTorch/pointnet2/train/train_sem_seg.py", line 11, in <module>
    from pointnet2.models import Pointnet2SemMSG as Pointnet
  File "/home/mengzhen/PointNet/Pointnet2_PyTorch/pointnet2/__init__.py", line 1, in <module>
    from . import utils
  File "/home/mengzhen/PointNet/Pointnet2_PyTorch/pointnet2/utils/__init__.py", line 1, in <module>
    from . import pointnet2_utils
  File "/home/mengzhen/PointNet/Pointnet2_PyTorch/pointnet2/utils/pointnet2_utils.py", line 10, in <module>
    from pointnet2.utils._ext import pointnet2
  File "/home/mengzhen/PointNet/Pointnet2_PyTorch/pointnet2/utils/_ext/pointnet2/__init__.py", line 3, in <module>
    from ._pointnet2 import lib as _lib, ffi as _ffi
ImportError: /home/mengzhen/PointNet/Pointnet2_PyTorch/pointnet2/utils/_ext/pointnet2/_pointnet2.so: undefined symbol: PyInt_FromLong

Process finished with exit code 1
could you help me?
Thank you very much!
Smm

**Comment by smmdream** [comment]
$ ldd _pointnet2.so 
and the output:
linux-vdso.so.1 =>  (0x00007fff66c95000)
libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007efc0f5ff000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007efc0f235000)
/lib64/ld-linux-x86-64.so.2 (0x00007efc0fab1000)

**Comment by erikwijmans** [comment]
And what version of python?

**Comment by erikwijmans** [comment]
I'm not sure.  I have never seen that error personally as I've ever only used this repo with python 3.6.

**Comment by erikwijmans** [comment]
Did a little googling, it seems that `PyInt_FromLong` is a python2 symbol and is not defined in python3.  I am guessing that this error is due to the build system finding python2.7.  Looking more carefully at your initial error log, you are specifying the exact version of python to run the script, but the build system just uses `python` (which probably picks up python2.7 on your system).

If you want to keep using python3, you will need to edit the cmake file here: https://github.com/erikwijmans/Pointnet2_PyTorch/blob/master/CMakeLists.txt#L12 to point to the specific version of python instead of just `python`.

If you want to use python2.7, there shouldn't be undefined symbol errors, but you will need to add the necessary `from __future__ import`'s.  If you add the `from __future__ import`'s please submit a PR!
