### ISSUE TITLE
ImportError: No module named 'pointnet2.utils._ext'

### ISSUE THREAD

**Issue by yanx27** [erikwijmans/Pointnet2_PyTorch#19]
Hello, I miss this problem:)

Traceback (most recent call last):
  File "E:/Github/Pointnet2_PyTorch/pointnet2/train/train_sem_seg.py", line 11, in <module>
    from pointnet2.models import Pointnet2SemMSG as Pointnet
  File "E:\Github\Pointnet2_PyTorch\pointnet2\__init__.py", line 1, in <module>
    from . import utils
  File "E:\Github\Pointnet2_PyTorch\pointnet2\utils\__init__.py", line 1, in <module>
    from . import pointnet2_utils
  File "E:\Github\Pointnet2_PyTorch\pointnet2\utils\pointnet2_utils.py", line 10, in <module>
    from pointnet2.utils._ext import pointnet2
ImportError: No module named 'pointnet2.utils._ext'

**Comment by erikwijmans** [comment]
Did you follow the build instructions?
