### ISSUE TITLE
issue to run the training after successful install 

### ISSUE THREAD

**Issue by GuesmiAbd** [erikwijmans/Pointnet2_PyTorch#35]
Hello, 

I have an issue to run the training after successful install of the repo. 
This is the command line and the generated error message. 

Thanks in advance, 
Raouf 

**python -m pointnet2.train.train_cls**

Traceback (most recent call last):
  File "/home/raouf/workspace/gitprojects/Pointnet2_PyTorch/pointnet2/utils/pointnet2_utils.py", line 20, in <module>
    import pointnet2._ext as _ext
ImportError: /home/raouf/workspace/gitprojects/Pointnet2_PyTorch/pointnet2/_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/raouf/anaconda3/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/raouf/anaconda3/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/raouf/workspace/gitprojects/Pointnet2_PyTorch/pointnet2/__init__.py", line 17, in <module>
    from pointnet2 import utils
  File "/home/raouf/workspace/gitprojects/Pointnet2_PyTorch/pointnet2/utils/__init__.py", line 8, in <module>
    from . import pointnet2_utils
  File "/home/raouf/workspace/gitprojects/Pointnet2_PyTorch/pointnet2/utils/pointnet2_utils.py", line 24, in <module>
    "Could not import _ext module.\n"
ImportError: Could not import _ext module.
Please see the setup instructions in the README: https://github.com/erikwijmans/Pointnet2_PyTorch/blob/master/README.rst

**Comment by erikwijmans** [comment]
This person seems to have the same issue and it was resolved: https://github.com/facebookresearch/maskrcnn-benchmark/issues/1

**Comment by dragonbook** [comment]
I had a similar issue([UndefinedTensorImpl10_singletonE ](https://github.com/NVIDIA/flownet2-pytorch/issues/116), [undefined symbol: __cudaPopCallConfiguration](https://github.com/horovod/horovod/issues/274)). Under Ubuntu16.04+cuda9.2, and the PyTorch was installed by "conda install pytorch torchvision cudatoolkit=9.0 -c pytorch", when import _ext module, there will be some undefined symbol errors. I finally fix it by reinstalling pytorch with cudatoolkit=9.2.
