### ISSUE TITLE
A mistake of running "train_cls.py" with CUDA 10.1 and Pytorch 1.3.0 On win10

### ISSUE THREAD

**Issue by Qinyike** [erikwijmans/Pointnet2_PyTorch#87]
Thank you so much for your work. I met A mistake of running "train_cls.py" with CUDA 10.1 and Pytorch 1.3.0 On win10. Could you please  help me?

ValueError: cannot find context for 'forkserver'

Error message:
(pointnet) λ python -m pointnet2.train.train_sem_seg
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\pointnet\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\ProgramData\Anaconda3\envs\pointnet\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Data\Desktop\Pointnet2_PyTorch-master\pointnet2\__init__.py", line 17, in <module>
    from pointnet2 import utils
  File "C:\Data\Desktop\Pointnet2_PyTorch-master\pointnet2\utils\__init__.py", line 8, in <module>
    from . import pointnet2_utils
  File "C:\Data\Desktop\Pointnet2_PyTorch-master\pointnet2\utils\pointnet2_utils.py", line 11, in <module>
    import etw_pytorch_utils as pt_utils
  File "C:\ProgramData\Anaconda3\envs\pointnet\lib\site-packages\etw_pytorch_utils\__init__.py", line 11, in <module>
    from .persistent_dataloader import DataLoader
  File "C:\ProgramData\Anaconda3\envs\pointnet\lib\site-packages\etw_pytorch_utils\persistent_dataloader.py", line 20, in <module>
    _mp_ctx = multiprocessing.get_context('forkserver')
  File "C:\ProgramData\Anaconda3\envs\pointnet\lib\multiprocessing\context.py", line 238, in get_context
    return super().get_context(method)
  File "C:\ProgramData\Anaconda3\envs\pointnet\lib\multiprocessing\context.py", line 192, in get_context
    raise ValueError('cannot find context for %r' % method) from None
ValueError: cannot find context for 'forkserver'

**Comment by erikwijmans** [comment]
This should be fixed now.
